package com.helpmi.domain.enums;

public enum AuditAction {
    PAT_CREATED,
    PAT_REVOKED,
    PAT_AUTH_SUCCESS,
    PAT_AUTH_FAILURE,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_ACTIVATED,
    USER_ORG_ADDED,
    USER_ORG_REMOVED,
    USER_PROJECTS_UPDATED,
    PROJECT_CREATED,
    PROJECT_ARCHIVED,
    PROJECT_UNARCHIVED,
    ORGANIZATION_CREATED,
    ORGANIZATION_DELETED,
    TICKET_DELETED,
    ATTACHMENT_DELETED,
    ACCESS_DENIED
}
