spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/helpmi
    username: helpmi
    password: helpmi_pass
  jpa:
    show-sql: false
  flyway:
    locations: classpath:db/migration,classpath:db/dev-seed

app:
  security:
    disabled: true
  dev:
    user-email: admin@helpmi.local
